#!/bin/sh

set casa = `pwd`
echo $casa

ls /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275074/ | grep Local > files

for rootfile in `cat files`
        do
        echo $rootfile
        cp /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275074//$rootfile .
        done

ls *.root > listoffilesLocalFinal.txt

cd ~/efficiency/timing/CMSSW_8_0_1/src/
eval `scramv1 ru -sh`
cd -

hadd Local.root Local*

cp listoffilesLocalFinal.txt /afs/cern.ch/user/c/carrillo/efficiency/timing/CMSSW_8_0_1/src/DQM/RPCMonitorModule/test/merging/275074
cp Local.root /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275074/

exit 0

