#!/bin/sh

set casa = `pwd`
echo $casa

ls /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275074/ | grep efficiency-275074 > files

for rootfile in `head -n 45 files | tail -n 15`
        do
        echo $rootfile
        cp /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275074//$rootfile .
        done

ls *.root > listoffilesLocal31-45.txt

cd ~/efficiency/timing/CMSSW_8_0_1/src/
eval `scramv1 ru -sh`
cd -

hadd Local31-45.root efficiency-275074*

cp listoffilesLocal31-45.txt /afs/cern.ch/user/c/carrillo/efficiency/timing/CMSSW_8_0_1/src/DQM/RPCMonitorModule/test/merging/275074
cp Local31-45.root /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275074/
exit 0

