#!/bin/sh

set casa = `pwd`
echo $casa

ls /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275067/ | grep efficiency > files

for rootfile in `head -n 75 files | tail -n 15`
        do
        echo $rootfile
        cp /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275067//$rootfile .
        done

ls *.root > listoffilesLocal61-75.txt

cd ~/efficiency/timing/CMSSW_8_0_1/src/
eval `scramv1 ru -sh`
cd -

hadd Local61-75.root efficiency*

cp listoffilesLocal61-75.txt /afs/cern.ch/user/c/carrillo/efficiency/timing/CMSSW_8_0_1/src/DQM/RPCMonitorModule/test/merging/275067
cp Local61-75.root /afs/cern.ch/work/c/carrillo/efficiencynoptt/_RPCMonitor_Run2016B-v2_RAW/275067/
exit 0

